version: '3.2'

services:
  elasticsearch-workshop-1:
    container_name: elasticsearch-workshop-1
    image: elasticsearch:7.6.2
    volumes:
      - "./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro"
      - "elasticsearch:/usr/share/elasticsearch/data"
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      # Use single node discovery in order to disable production mode and avoid bootstrap checks
      # see https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html
      discovery.type: single-node
    networks:
      - elk

  logstash:
    container_name: logstash
    image: logstash:7.6.2
    volumes:
      - "./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro"
      - "./logstash/pipeline:/usr/share/logstash/pipeline:ro"
    ports:
      - "5000:5000/tcp"
      - "5000:5000/udp"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    depends_on:
      - elasticsearch-workshop-1

  kibana:
    container_name: kibana
    image: kibana:7.6.2
    volumes:
      - "./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro"
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch-workshop-1
      
  cerebro:
    container_name: cerebro
    image: lmenezes/cerebro
    ports:
      - "9000:9000"
    networks:
      - elk
    depends_on: 
      - elasticsearch-workshop-1

networks:
  elk:
    driver: bridge

volumes:
  elasticsearch:
